from __future__ import annotations

from datetime import datetime, time, timedelta

VEHICLE_MARKING_SENTENCE = {
    "en": "Our vehicle is marked with a 'VIP Catamaran' sign, so you can recognize it easily.",
    "de": 'Unser Fahrzeug ist mit einem Schild „VIP Catamaran" gekennzeichnet, damit Sie es leicht erkennen können.',
    "es": "Nuestro vehículo lleva un cartel con el nombre «VIP Catamaran», para que pueda reconocerlo fácilmente.",
    "fr": "Notre véhicule porte un panneau « VIP Catamaran », afin que vous puissiez le reconnaître facilement.",
    "it": "Il nostro mezzo è contrassegnato da un cartello con la scritta «VIP Catamaran», così potrà riconoscerlo facilmente.",
    "el": "Το όχημά μας φέρει πινακίδα με την ένδειξη «VIP Catamaran», ώστε να το αναγνωρίζετε εύκολα.",
}

VEHICLE_RECOGNITION_MARKERS = {
    "en": (("vip catamaran",), ("sign",), ("recognize", "recognise", "identify")),
    "de": (("vip catamaran",), ("schild",), ("erkennen",)),
    "es": (("vip catamaran",), ("cartel",), ("identific", "reconoc")),
    "fr": (("vip catamaran",), ("panneau",), ("reconna",)),
    "it": (("vip catamaran",), ("cartello",), ("riconosc",)),
    "el": (("vip catamaran",), ("πινακ",), ("αναγνωρ",)),
}

# This pickup point is a direct meet-at-the-boat instruction, not a vehicle stop.
# Keep the no-vehicle rule explicit so future wording edits do not accidentally
# reintroduce the shared vehicle-sign sentence in any language.
NO_VEHICLE_PICKUP_POINTS = {"Meet at Catamaran"}

OFFICIAL_PICKUP_COPY = {
    "en": {
        "Vlas - Petrol Station": 'Please find attached a link to the pickup point that you have selected. It is the bus stop on the main road at the roundabout next to the petrol station in Sveti Vlas. Our big red London double-decker bus will be there at {pickup_time} to collect you.',
        "Mercury Grand Market": 'Please find attached a link to the pickup point that you have selected. It is the bus stop on the main road next to Mercury Grand Market. Our big red London double-decker bus will be there at {pickup_time} to collect you.',
        "Secrets Resort - Main Road Bus Stop": 'Please find attached a link to the pickup point that you have selected. It is the bus stop on the main road opposite Secrets Sunny Beach Resort and Spa. Our big red London double-decker bus will be there at {pickup_time} to collect you.',
        "Helena / Zora - Main Road Bus Stop": 'Please find attached a link to the pickup point that you have selected. It is the bus stop on the main road running through the resort next to Aldo Supermarket. Our big red London double-decker bus will be there at {pickup_time} to collect you.',
        "Efir Bus Stop": 'Please find attached a link to the pickup point that you have selected. It is the bus stop on the main road running through the resort, next to Hotel Efir. Our big red London double-decker bus will be there at {pickup_time} to collect you.',
        "Palm Court Bus Stop": 'Please find attached a link to the pickup point that you have selected. It is the bus stop on the main road running through the resort, opposite Hotel Riva. Our big red London double-decker bus will be there at {pickup_time} to collect you.',
        "Opal Bus Stop": 'Please find attached a link to the pickup point that you have selected. It is the bus stop on the main road running through the resort, in front of Hotel Opal. Our big red London double-decker bus will be there at {pickup_time} to collect you.',
        "Flower Street Main Bus Stop": 'Please find attached a link to the pickup point that you have selected. It is the bus stop opposite the main pedestrian street in Sunny Beach. Our big red London double-decker bus will be there at {pickup_time} to collect you.',
        "Hotel Best Western / Sveshest": 'Please find attached a link to the pickup point that you have selected. It is the bus stop on the main road behind the Best Western Hotel and next to Spider\'s pub. Our big red London double-decker bus will be there at {pickup_time} to collect you.',
        "Royal Sun / Arda Bus Stop": 'Please find attached a link to the pickup point that you have selected. It is the bus stop on the main road running through the resort, next to The Royal Sun Complex. Our big red London double-decker bus will be there at {pickup_time} to collect you.',
        "Persani (Black Sea Hotel Bus Stop)": 'Please find attached a link to the pickup point that you have selected. It is the bus stop on the main road running through the resort, next to Hotel Persani. Our big red London double-decker bus will be there at {pickup_time} to collect you.',
        "Belleville / Cacao Bus Stop": 'Please find attached a link to the pickup point that you have selected. It is the bus stop on the main road running through the resort, next to Hotel BelleVille. Our big red London double-decker bus will be there at {pickup_time} to collect you.',
        "Football Stadium Bus Stop": 'Please find attached a link to the pickup point that you have selected. It is the bus stop on the main road running through the resort, next to Hotel The Step and Diamant Residence. Our big red London double-decker bus will be there at {pickup_time} to collect you.',
        "Festa Panorama Ness Bus Stop": 'Please find attached a link to the pickup point that you have selected. It is the bus stop on the main road opposite Hotel Festa Panorama. Our big red London double-decker bus will be there at {pickup_time} to collect you.',
        "Aqua Paradise Hotel - with Minibus": 'Please find attached a link to the pickup point you have selected. Our transport will be outside Aqua Paradise Hotel at {pickup_time} to collect you. You can identify our minibus by the "VIP Catamaran" sign on the front window.',
        "SOL Nessebar Palas - with Minibus": 'Please find attached a link to the pickup point that you have selected. It is located at the barrier next to SOL Nessebar Palace Hotel. Our transport will be there at {pickup_time} to collect you. You can identify our minibus by the "VIP Catamaran" sign on the front window.',
        "Panteleimon Bus Stop - with Minibus": 'Please find attached a link to the pickup point that you have selected. It is the bus stop Panteleimon, number 36, which is located on the main road. Our transport will be there at {pickup_time} to collect you. You can identify our minibus by the "VIP Catamaran" sign on the front window.',
        "Biliyana Ness - with Minibus": 'Please find attached a link to the pickup point that you have selected. It is the bus stop on the main road near the Bilyana Beach Hotel. Our transport will be there at {pickup_time} to collect you. You can identify our minibus by the "VIP Catamaran" sign on the front window.',
        "Oasis Ness - with Minibus": 'Please find attached a link to the pickup point that you have selected. It is the bus stop on the road, next to Bistro Oasis. Our guide and transportation will be there at {pickup_time} to collect you. You can identify our minibus by the "VIP Catamaran" sign on the front window.',
        "Marina Palas - with Minibus": 'Please find attached a link to the pickup point that you have selected. It is located right outside Hotel Sol Marina Palace. Our transport will be there at {pickup_time} to collect you. You can recognise our minibus by the VIP Catamaran sign on the front window.',
        "Meet at Catamaran": 'Please find attached a link to the exact location of our catamaran. Please be there by {arrival_time} as we sail away at {cruise_time}.',
    },
    "es": {
        "Vlas - Petrol Station": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la parada de autobús de la carretera principal, en la rotonda junto a la gasolinera de Sveti Vlas. Nuestro gran autobús rojo de dos pisos estilo Londres estará allí a las {pickup_time} para recogerle.',
        "Mercury Grand Market": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la parada de autobús de la carretera principal junto a Mercury Grand Market. Nuestro gran autobús rojo de dos pisos estilo Londres estará allí a las {pickup_time} para recogerle.',
        "Secrets Resort - Main Road Bus Stop": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la parada de autobús de la carretera principal frente a Secrets Sunny Beach Resort and Spa. Nuestro gran autobús rojo de dos pisos estilo Londres estará allí a las {pickup_time} para recogerle.',
        "Helena / Zora - Main Road Bus Stop": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la parada de autobús de la carretera principal que atraviesa el complejo, junto al supermercado Aldo. Nuestro gran autobús rojo de dos pisos estilo Londres estará allí a las {pickup_time} para recogerle.',
        "Efir Bus Stop": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la parada de autobús de la carretera principal que atraviesa el complejo, junto al Hotel Efir. Nuestro gran autobús rojo de dos pisos estilo Londres estará allí a las {pickup_time} para recogerle.',
        "Palm Court Bus Stop": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la parada de autobús de la carretera principal que atraviesa el complejo, frente al Hotel Riva. Nuestro gran autobús rojo de dos pisos estilo Londres estará allí a las {pickup_time} para recogerle.',
        "Opal Bus Stop": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la parada de autobús de la carretera principal que atraviesa el complejo, delante del Hotel Opal. Nuestro gran autobús rojo de dos pisos estilo Londres estará allí a las {pickup_time} para recogerle.',
        "Flower Street Main Bus Stop": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la parada de autobús frente a la calle peatonal principal de Sunny Beach. Nuestro gran autobús rojo de dos pisos estilo Londres estará allí a las {pickup_time} para recogerle.',
        "Hotel Best Western / Sveshest": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la parada de autobús de la carretera principal, detrás del Hotel Best Western y junto al pub Spider\'s. Nuestro gran autobús rojo de dos pisos estilo Londres estará allí a las {pickup_time} para recogerle.',
        "Royal Sun / Arda Bus Stop": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la parada de autobús de la carretera principal que atraviesa el complejo, junto al complejo The Royal Sun. Nuestro gran autobús rojo de dos pisos estilo Londres estará allí a las {pickup_time} para recogerle.',
        "Persani (Black Sea Hotel Bus Stop)": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la parada de autobús de la carretera principal que atraviesa el complejo, junto al Hotel Persani. Nuestro gran autobús rojo de dos pisos estilo Londres estará allí a las {pickup_time} para recogerle.',
        "Belleville / Cacao Bus Stop": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la parada de autobús de la carretera principal que atraviesa el complejo, junto al Hotel BelleVille. Nuestro gran autobús rojo de dos pisos estilo Londres estará allí a las {pickup_time} para recogerle.',
        "Football Stadium Bus Stop": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la parada de autobús de la carretera principal que atraviesa el complejo, junto al Hotel The Step y Diamant Residence. Nuestro gran autobús rojo de dos pisos estilo Londres estará allí a las {pickup_time} para recogerle.',
        "Festa Panorama Ness Bus Stop": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la parada de autobús de la carretera principal frente al Hotel Festa Panorama. Nuestro gran autobús rojo de dos pisos estilo Londres estará allí a las {pickup_time} para recogerle.',
        "Aqua Paradise Hotel - with Minibus": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Nuestro transporte estará fuera del Aqua Paradise Hotel a las {pickup_time} para recogerle. Puede identificar nuestro minibús por el cartel "VIP Catamaran" en el parabrisas delantero.',
        "SOL Nessebar Palas - with Minibus": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la barrera junto al Hotel SOL Nessebar Palace. Nuestro transporte estará allí a las {pickup_time} para recogerle. Puede identificar nuestro minibús por el cartel "VIP Catamaran" en el parabrisas delantero.',
        "Panteleimon Bus Stop - with Minibus": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la parada de autobús Panteleimon, número 36, situada en la carretera principal. Nuestro transporte estará allí a las {pickup_time} para recogerle. Puede identificar nuestro minibús por el cartel "VIP Catamaran" en el parabrisas delantero.',
        "Biliyana Ness - with Minibus": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la parada de autobús de la carretera principal cerca del Hotel Bilyana Beach. Nuestro transporte estará allí a las {pickup_time} para recogerle. Puede identificar nuestro minibús por el cartel "VIP Catamaran" en el parabrisas delantero.',
        "Oasis Ness - with Minibus": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra en la parada de autobús de la carretera, junto a Bistro Oasis. Nuestro guía y el transporte estarán allí a las {pickup_time} para recogerle. Puede identificar nuestro minibús por el cartel "VIP Catamaran" en el parabrisas delantero.',
        "Marina Palas - with Minibus": 'Adjuntamos un enlace al punto de recogida que ha seleccionado. Se encuentra justo fuera del Hotel Sol Marina Palace. Nuestro transporte estará allí a las {pickup_time} para recogerle. Puede reconocer nuestro minibús por el cartel VIP Catamaran en el parabrisas delantero.',
        "Meet at Catamaran": 'Adjuntamos un enlace con la ubicación exacta de nuestro catamarán. Por favor, esté allí antes de las {arrival_time}, ya que zarpamos a las {cruise_time}.',
    },
    "fr": {
        "Vlas - Petrol Station": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à l\'arrêt de bus sur la route principale, au rond-point à côté de la station-service de Sveti Vlas. Notre grand bus rouge à impériale de style londonien sera là à {pickup_time} pour venir vous chercher.',
        "Mercury Grand Market": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à l\'arrêt de bus sur la route principale à côté de Mercury Grand Market. Notre grand bus rouge à impériale de style londonien sera là à {pickup_time} pour venir vous chercher.',
        "Secrets Resort - Main Road Bus Stop": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à l\'arrêt de bus sur la route principale en face de Secrets Sunny Beach Resort and Spa. Notre grand bus rouge à impériale de style londonien sera là à {pickup_time} pour venir vous chercher.',
        "Helena / Zora - Main Road Bus Stop": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à l\'arrêt de bus sur la route principale qui traverse la station, à côté du supermarché Aldo. Notre grand bus rouge à impériale de style londonien sera là à {pickup_time} pour venir vous chercher.',
        "Efir Bus Stop": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à l\'arrêt de bus sur la route principale qui traverse la station, à côté de l\'hôtel Efir. Notre grand bus rouge à impériale de style londonien sera là à {pickup_time} pour venir vous chercher.',
        "Palm Court Bus Stop": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à l\'arrêt de bus sur la route principale qui traverse la station, en face de l\'hôtel Riva. Notre grand bus rouge à impériale de style londonien sera là à {pickup_time} pour venir vous chercher.',
        "Opal Bus Stop": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à l\'arrêt de bus sur la route principale qui traverse la station, devant l\'hôtel Opal. Notre grand bus rouge à impériale de style londonien sera là à {pickup_time} pour venir vous chercher.',
        "Flower Street Main Bus Stop": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à l\'arrêt de bus en face de la rue piétonne principale de Sunny Beach. Notre grand bus rouge à impériale de style londonien sera là à {pickup_time} pour venir vous chercher.',
        "Hotel Best Western / Sveshest": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à l\'arrêt de bus sur la route principale derrière l\'hôtel Best Western et à côté du pub Spider\'s. Notre grand bus rouge à impériale de style londonien sera là à {pickup_time} pour venir vous chercher.',
        "Royal Sun / Arda Bus Stop": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à l\'arrêt de bus sur la route principale qui traverse la station, à côté du complexe The Royal Sun. Notre grand bus rouge à impériale de style londonien sera là à {pickup_time} pour venir vous chercher.',
        "Persani (Black Sea Hotel Bus Stop)": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à l\'arrêt de bus sur la route principale qui traverse la station, à côté de l\'hôtel Persani. Notre grand bus rouge à impériale de style londonien sera là à {pickup_time} pour venir vous chercher.',
        "Belleville / Cacao Bus Stop": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à l\'arrêt de bus sur la route principale qui traverse la station, à côté de l\'hôtel BelleVille. Notre grand bus rouge à impériale de style londonien sera là à {pickup_time} pour venir vous chercher.',
        "Football Stadium Bus Stop": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à l\'arrêt de bus sur la route principale qui traverse la station, à côté de l\'hôtel The Step et du Diamant Residence. Notre grand bus rouge à impériale de style londonien sera là à {pickup_time} pour venir vous chercher.',
        "Festa Panorama Ness Bus Stop": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à l\'arrêt de bus sur la route principale en face de l\'hôtel Festa Panorama. Notre grand bus rouge à impériale de style londonien sera là à {pickup_time} pour venir vous chercher.',
        "Aqua Paradise Hotel - with Minibus": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Notre transport sera devant l\'hôtel Aqua Paradise à {pickup_time} pour venir vous chercher. Vous pouvez reconnaître notre minibus grâce au panneau "VIP Catamaran" sur le pare-brise avant.',
        "SOL Nessebar Palas - with Minibus": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à la barrière à côté de l\'hôtel SOL Nessebar Palace. Notre transport sera là à {pickup_time} pour venir vous chercher. Vous pouvez reconnaître notre minibus grâce au panneau "VIP Catamaran" sur le pare-brise avant.',
        "Panteleimon Bus Stop - with Minibus": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à l\'arrêt de bus Panteleimon, numéro 36, situé sur la route principale. Notre transport sera là à {pickup_time} pour venir vous chercher. Vous pouvez reconnaître notre minibus grâce au panneau "VIP Catamaran" sur le pare-brise avant.',
        "Biliyana Ness - with Minibus": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à l\'arrêt de bus sur la route principale près de l\'hôtel Bilyana Beach. Notre transport sera là à {pickup_time} pour venir vous chercher. Vous pouvez reconnaître notre minibus grâce au panneau "VIP Catamaran" sur le pare-brise avant.',
        "Oasis Ness - with Minibus": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve à l\'arrêt de bus sur la route, à côté du Bistro Oasis. Notre guide et le transport seront là à {pickup_time} pour venir vous chercher. Vous pouvez reconnaître notre minibus grâce au panneau "VIP Catamaran" sur le pare-brise avant.',
        "Marina Palas - with Minibus": 'Veuillez trouver ci-joint le lien vers le point de prise en charge que vous avez sélectionné. Il se trouve juste devant l\'hôtel Sol Marina Palace. Notre transport sera là à {pickup_time} pour venir vous chercher. Vous pouvez reconnaître notre minibus grâce au panneau VIP Catamaran sur le pare-brise avant.',
        "Meet at Catamaran": 'Veuillez trouver ci-joint le lien vers l\'emplacement exact de notre catamaran. Veuillez être sur place avant {arrival_time}, car nous appareillons à {cruise_time}.',
    },
    "de": {
        "Vlas - Petrol Station": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Es handelt sich um die Bushaltestelle an der Hauptstraße am Kreisverkehr neben der Tankstelle in Sveti Vlas. Unser großer roter Londoner Doppeldeckerbus wird Sie dort um {pickup_time} abholen.',
        "Mercury Grand Market": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Es handelt sich um die Bushaltestelle an der Hauptstraße neben dem Mercury Grand Market. Unser großer roter Londoner Doppeldeckerbus wird Sie dort um {pickup_time} abholen.',
        "Secrets Resort - Main Road Bus Stop": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Es handelt sich um die Bushaltestelle an der Hauptstraße gegenüber dem Secrets Sunny Beach Resort and Spa. Unser großer roter Londoner Doppeldeckerbus wird Sie dort um {pickup_time} abholen.',
        "Helena / Zora - Main Road Bus Stop": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Es handelt sich um die Bushaltestelle an der Hauptstraße durch das Resort, neben dem Aldo Supermarket. Unser großer roter Londoner Doppeldeckerbus wird Sie dort um {pickup_time} abholen.',
        "Efir Bus Stop": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Es handelt sich um die Bushaltestelle an der Hauptstraße durch das Resort, neben dem Hotel Efir. Unser großer roter Londoner Doppeldeckerbus wird Sie dort um {pickup_time} abholen.',
        "Palm Court Bus Stop": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Es handelt sich um die Bushaltestelle an der Hauptstraße durch das Resort, gegenüber dem Hotel Riva. Unser großer roter Londoner Doppeldeckerbus wird Sie dort um {pickup_time} abholen.',
        "Opal Bus Stop": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Es handelt sich um die Bushaltestelle an der Hauptstraße durch das Resort, vor dem Hotel Opal. Unser großer roter Londoner Doppeldeckerbus wird Sie dort um {pickup_time} abholen.',
        "Flower Street Main Bus Stop": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Es handelt sich um die Bushaltestelle gegenüber der Hauptfußgängerzone in Sunny Beach. Unser großer roter Londoner Doppeldeckerbus wird Sie dort um {pickup_time} abholen.',
        "Hotel Best Western / Sveshest": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Es handelt sich um die Bushaltestelle an der Hauptstraße hinter dem Best Western Hotel und neben Spider\'s Pub. Unser großer roter Londoner Doppeldeckerbus wird Sie dort um {pickup_time} abholen.',
        "Royal Sun / Arda Bus Stop": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Es handelt sich um die Bushaltestelle an der Hauptstraße durch das Resort, neben dem The Royal Sun Complex. Unser großer roter Londoner Doppeldeckerbus wird Sie dort um {pickup_time} abholen.',
        "Persani (Black Sea Hotel Bus Stop)": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Es handelt sich um die Bushaltestelle an der Hauptstraße durch das Resort, neben dem Hotel Persani. Unser großer roter Londoner Doppeldeckerbus wird Sie dort um {pickup_time} abholen.',
        "Belleville / Cacao Bus Stop": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Es handelt sich um die Bushaltestelle an der Hauptstraße durch das Resort, neben dem Hotel BelleVille. Unser großer roter Londoner Doppeldeckerbus wird Sie dort um {pickup_time} abholen.',
        "Football Stadium Bus Stop": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Es handelt sich um die Bushaltestelle an der Hauptstraße durch das Resort, neben dem Hotel The Step und dem Diamant Residence. Unser großer roter Londoner Doppeldeckerbus wird Sie dort um {pickup_time} abholen.',
        "Festa Panorama Ness Bus Stop": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Es handelt sich um die Bushaltestelle an der Hauptstraße gegenüber dem Hotel Festa Panorama. Unser großer roter Londoner Doppeldeckerbus wird Sie dort um {pickup_time} abholen.',
        "Aqua Paradise Hotel - with Minibus": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Unser Transfer wird Sie um {pickup_time} vor dem Aqua Paradise Hotel abholen. Sie erkennen unseren Minibus an dem "VIP Catamaran"-Schild in der Frontscheibe.',
        "SOL Nessebar Palas - with Minibus": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Er befindet sich an der Schranke neben dem Hotel SOL Nessebar Palace. Unser Transfer wird Sie dort um {pickup_time} abholen. Sie erkennen unseren Minibus an dem "VIP Catamaran"-Schild in der Frontscheibe.',
        "Panteleimon Bus Stop - with Minibus": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Es handelt sich um die Bushaltestelle Panteleimon, Nummer 36, an der Hauptstraße. Unser Transfer wird Sie dort um {pickup_time} abholen. Sie erkennen unseren Minibus an dem "VIP Catamaran"-Schild in der Frontscheibe.',
        "Biliyana Ness - with Minibus": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Es handelt sich um die Bushaltestelle an der Hauptstraße in der Nähe des Hotels Bilyana Beach. Unser Transfer wird Sie dort um {pickup_time} abholen. Sie erkennen unseren Minibus an dem "VIP Catamaran"-Schild in der Frontscheibe.',
        "Oasis Ness - with Minibus": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Es handelt sich um die Bushaltestelle an der Straße neben dem Bistro Oasis. Unser Reiseleiter und der Transfer werden Sie dort um {pickup_time} abholen. Sie erkennen unseren Minibus an dem "VIP Catamaran"-Schild in der Frontscheibe.',
        "Marina Palas - with Minibus": 'Hier finden Sie den Link zu dem von Ihnen ausgewählten Abholpunkt. Er befindet sich direkt vor dem Hotel Sol Marina Palace. Unser Transfer wird Sie dort um {pickup_time} abholen. Sie erkennen unseren Minibus an dem VIP Catamaran-Schild in der Frontscheibe.',
        "Meet at Catamaran": 'Hier finden Sie den Link zum genauen Standort unseres Katamarans. Bitte seien Sie bis {arrival_time} dort, da wir um {cruise_time} ablegen.',
    },
    "it": {
        "Vlas - Petrol Station": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si tratta della fermata dell\'autobus sulla strada principale, alla rotonda accanto alla stazione di servizio di Sveti Vlas. Il nostro grande autobus rosso a due piani stile Londra sarà lì alle {pickup_time} per venirla a prendere.',
        "Mercury Grand Market": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si tratta della fermata dell\'autobus sulla strada principale accanto al Mercury Grand Market. Il nostro grande autobus rosso a due piani stile Londra sarà lì alle {pickup_time} per venirla a prendere.',
        "Secrets Resort - Main Road Bus Stop": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si tratta della fermata dell\'autobus sulla strada principale di fronte al Secrets Sunny Beach Resort and Spa. Il nostro grande autobus rosso a due piani stile Londra sarà lì alle {pickup_time} per venirla a prendere.',
        "Helena / Zora - Main Road Bus Stop": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si tratta della fermata dell\'autobus sulla strada principale che attraversa il resort, accanto al supermercato Aldo. Il nostro grande autobus rosso a due piani stile Londra sarà lì alle {pickup_time} per venirla a prendere.',
        "Efir Bus Stop": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si tratta della fermata dell\'autobus sulla strada principale che attraversa il resort, accanto all\'Hotel Efir. Il nostro grande autobus rosso a due piani stile Londra sarà lì alle {pickup_time} per venirla a prendere.',
        "Palm Court Bus Stop": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si tratta della fermata dell\'autobus sulla strada principale che attraversa il resort, di fronte all\'Hotel Riva. Il nostro grande autobus rosso a due piani stile Londra sarà lì alle {pickup_time} per venirla a prendere.',
        "Opal Bus Stop": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si tratta della fermata dell\'autobus sulla strada principale che attraversa il resort, di fronte all\'Hotel Opal. Il nostro grande autobus rosso a due piani stile Londra sarà lì alle {pickup_time} per venirla a prendere.',
        "Flower Street Main Bus Stop": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si tratta della fermata dell\'autobus di fronte alla principale via pedonale di Sunny Beach. Il nostro grande autobus rosso a due piani stile Londra sarà lì alle {pickup_time} per venirla a prendere.',
        "Hotel Best Western / Sveshest": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si tratta della fermata dell\'autobus sulla strada principale dietro il Best Western Hotel e accanto al pub Spider\'s. Il nostro grande autobus rosso a due piani stile Londra sarà lì alle {pickup_time} per venirla a prendere.',
        "Royal Sun / Arda Bus Stop": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si tratta della fermata dell\'autobus sulla strada principale che attraversa il resort, accanto al complesso The Royal Sun. Il nostro grande autobus rosso a due piani stile Londra sarà lì alle {pickup_time} per venirla a prendere.',
        "Persani (Black Sea Hotel Bus Stop)": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si tratta della fermata dell\'autobus sulla strada principale che attraversa il resort, accanto all\'Hotel Persani. Il nostro grande autobus rosso a due piani stile Londra sarà lì alle {pickup_time} per venirla a prendere.',
        "Belleville / Cacao Bus Stop": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si tratta della fermata dell\'autobus sulla strada principale che attraversa il resort, accanto all\'Hotel BelleVille. Il nostro grande autobus rosso a due piani stile Londra sarà lì alle {pickup_time} per venirla a prendere.',
        "Football Stadium Bus Stop": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si tratta della fermata dell\'autobus sulla strada principale che attraversa il resort, accanto all\'Hotel The Step e al Diamant Residence. Il nostro grande autobus rosso a due piani stile Londra sarà lì alle {pickup_time} per venirla a prendere.',
        "Festa Panorama Ness Bus Stop": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si tratta della fermata dell\'autobus sulla strada principale di fronte all\'Hotel Festa Panorama. Il nostro grande autobus rosso a due piani stile Londra sarà lì alle {pickup_time} per venirla a prendere.',
        "Aqua Paradise Hotel - with Minibus": 'Di seguito trova il link al punto di prelievo che ha selezionato. Il nostro trasporto sarà fuori dall\'Aqua Paradise Hotel alle {pickup_time} per venirla a prendere. Può riconoscere il nostro minibus dal cartello "VIP Catamaran" sul parabrezza anteriore.',
        "SOL Nessebar Palas - with Minibus": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si trova alla barriera accanto all\'Hotel SOL Nessebar Palace. Il nostro trasporto sarà lì alle {pickup_time} per venirla a prendere. Può riconoscere il nostro minibus dal cartello "VIP Catamaran" sul parabrezza anteriore.',
        "Panteleimon Bus Stop - with Minibus": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si tratta della fermata dell\'autobus Panteleimon, numero 36, situata sulla strada principale. Il nostro trasporto sarà lì alle {pickup_time} per venirla a prendere. Può riconoscere il nostro minibus dal cartello "VIP Catamaran" sul parabrezza anteriore.',
        "Biliyana Ness - with Minibus": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si tratta della fermata dell\'autobus sulla strada principale vicino all\'Hotel Bilyana Beach. Il nostro trasporto sarà lì alle {pickup_time} per venirla a prendere. Può riconoscere il nostro minibus dal cartello "VIP Catamaran" sul parabrezza anteriore.',
        "Oasis Ness - with Minibus": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si tratta della fermata dell\'autobus sulla strada, accanto al Bistro Oasis. La nostra guida e il trasporto saranno lì alle {pickup_time} per venirla a prendere. Può riconoscere il nostro minibus dal cartello "VIP Catamaran" sul parabrezza anteriore.',
        "Marina Palas - with Minibus": 'Di seguito trova il link al punto di prelievo che ha selezionato. Si trova proprio fuori dall\'Hotel Sol Marina Palace. Il nostro trasporto sarà lì alle {pickup_time} per venirla a prendere. Può riconoscere il nostro minibus dal cartello VIP Catamaran sul parabrezza anteriore.',
        "Meet at Catamaran": 'Di seguito trova il link con la posizione esatta del nostro catamarano. La preghiamo di essere lì entro le {arrival_time}, poiché salpiamo alle {cruise_time}.',
    },
    "el": {
        "Vlas - Petrol Station": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Πρόκειται για τη στάση λεωφορείου στον κεντρικό δρόμο, στον κυκλικό κόμβο δίπλα στο βενζινάδικο στο Sveti Vlas. Το μεγάλο κόκκινο λονδρέζικο διώροφο λεωφορείο μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει.',
        "Mercury Grand Market": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Πρόκειται για τη στάση λεωφορείου στον κεντρικό δρόμο δίπλα στο Mercury Grand Market. Το μεγάλο κόκκινο λονδρέζικο διώροφο λεωφορείο μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει.',
        "Secrets Resort - Main Road Bus Stop": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Πρόκειται για τη στάση λεωφορείου στον κεντρικό δρόμο απέναντι από το Secrets Sunny Beach Resort and Spa. Το μεγάλο κόκκινο λονδρέζικο διώροφο λεωφορείο μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει.',
        "Helena / Zora - Main Road Bus Stop": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Πρόκειται για τη στάση λεωφορείου στον κεντρικό δρόμο που διασχίζει το θέρετρο, δίπλα στο σούπερ μάρκετ Aldo. Το μεγάλο κόκκινο λονδρέζικο διώροφο λεωφορείο μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει.',
        "Efir Bus Stop": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Πρόκειται για τη στάση λεωφορείου στον κεντρικό δρόμο που διασχίζει το θέρετρο, δίπλα στο Hotel Efir. Το μεγάλο κόκκινο λονδρέζικο διώροφο λεωφορείο μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει.',
        "Palm Court Bus Stop": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Πρόκειται για τη στάση λεωφορείου στον κεντρικό δρόμο που διασχίζει το θέρετρο, απέναντι από το Hotel Riva. Το μεγάλο κόκκινο λονδρέζικο διώροφο λεωφορείο μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει.',
        "Opal Bus Stop": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Πρόκειται για τη στάση λεωφορείου στον κεντρικό δρόμο που διασχίζει το θέρετρο, μπροστά από το Hotel Opal. Το μεγάλο κόκκινο λονδρέζικο διώροφο λεωφορείο μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει.',
        "Flower Street Main Bus Stop": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Πρόκειται για τη στάση λεωφορείου απέναντι από τον κεντρικό πεζόδρομο του Sunny Beach. Το μεγάλο κόκκινο λονδρέζικο διώροφο λεωφορείο μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει.',
        "Hotel Best Western / Sveshest": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Πρόκειται για τη στάση λεωφορείου στον κεντρικό δρόμο πίσω από το ξενοδοχείο Best Western και δίπλα στο Spider\'s pub. Το μεγάλο κόκκινο λονδρέζικο διώροφο λεωφορείο μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει.',
        "Royal Sun / Arda Bus Stop": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Πρόκειται για τη στάση λεωφορείου στον κεντρικό δρόμο που διασχίζει το θέρετρο, δίπλα στο συγκρότημα The Royal Sun. Το μεγάλο κόκκινο λονδρέζικο διώροφο λεωφορείο μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει.',
        "Persani (Black Sea Hotel Bus Stop)": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Πρόκειται για τη στάση λεωφορείου στον κεντρικό δρόμο που διασχίζει το θέρετρο, δίπλα στο Hotel Persani. Το μεγάλο κόκκινο λονδρέζικο διώροφο λεωφορείο μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει.',
        "Belleville / Cacao Bus Stop": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Πρόκειται για τη στάση λεωφορείου στον κεντρικό δρόμο που διασχίζει το θέρετρο, δίπλα στο Hotel BelleVille. Το μεγάλο κόκκινο λονδρέζικο διώροφο λεωφορείο μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει.',
        "Football Stadium Bus Stop": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Πρόκειται για τη στάση λεωφορείου στον κεντρικό δρόμο που διασχίζει το θέρετρο, δίπλα στο Hotel The Step και στο Diamant Residence. Το μεγάλο κόκκινο λονδρέζικο διώροφο λεωφορείο μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει.',
        "Festa Panorama Ness Bus Stop": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Πρόκειται για τη στάση λεωφορείου στον κεντρικό δρόμο απέναντι από το Hotel Festa Panorama. Το μεγάλο κόκκινο λονδρέζικο διώροφο λεωφορείο μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει.',
        "Aqua Paradise Hotel - with Minibus": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Η μεταφορά μας θα βρίσκεται έξω από το Aqua Paradise Hotel στις {pickup_time} για να σας παραλάβει. Μπορείτε να αναγνωρίσετε το minibus μας από την πινακίδα "VIP Catamaran" στο μπροστινό παρμπρίζ.',
        "SOL Nessebar Palas - with Minibus": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Βρίσκεται στη μπάρα δίπλα στο Hotel SOL Nessebar Palace. Η μεταφορά μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει. Μπορείτε να αναγνωρίσετε το minibus μας από την πινακίδα "VIP Catamaran" στο μπροστινό παρμπρίζ.',
        "Panteleimon Bus Stop - with Minibus": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Πρόκειται για τη στάση λεωφορείου Panteleimon, αριθμός 36, που βρίσκεται στον κεντρικό δρόμο. Η μεταφορά μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει. Μπορείτε να αναγνωρίσετε το minibus μας από την πινακίδα "VIP Catamaran" στο μπροστινό παρμπρίζ.',
        "Biliyana Ness - with Minibus": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Πρόκειται για τη στάση λεωφορείου στον κεντρικό δρόμο κοντά στο Hotel Bilyana Beach. Η μεταφορά μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει. Μπορείτε να αναγνωρίσετε το minibus μας από την πινακίδα "VIP Catamaran" στο μπροστινό παρμπρίζ.',
        "Oasis Ness - with Minibus": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Πρόκειται για τη στάση λεωφορείου στον δρόμο, δίπλα στο Bistro Oasis. Ο ξεναγός μας και η μεταφορά θα είναι εκεί στις {pickup_time} για να σας παραλάβουν. Μπορείτε να αναγνωρίσετε το minibus μας από την πινακίδα "VIP Catamaran" στο μπροστινό παρμπρίζ.',
        "Marina Palas - with Minibus": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο για το σημείο παραλαβής που έχετε επιλέξει. Βρίσκεται ακριβώς έξω από το Hotel Sol Marina Palace. Η μεταφορά μας θα είναι εκεί στις {pickup_time} για να σας παραλάβει. Μπορείτε να αναγνωρίσετε το minibus μας από την πινακίδα VIP Catamaran στο μπροστινό παρμπρίζ.',
        "Meet at Catamaran": 'Παρακαλούμε βρείτε συνημμένο τον σύνδεσμο με την ακριβή τοποθεσία του καταμαράν μας. Παρακαλούμε να είστε εκεί μέχρι τις {arrival_time}, καθώς αναχωρούμε στις {cruise_time}.',
    },
}


def _format_time(value: time | None, fallback: str) -> str:
    return value.strftime("%H:%M") if value else fallback


def _arrival_time_for_cruise(cruise_time: time | None, fallback: str) -> str:
    if cruise_time is None:
        return fallback
    cruise_moment = datetime.combine(datetime.today().date(), cruise_time)
    return (cruise_moment - timedelta(minutes=10)).strftime("%H:%M")


def _has_vehicle_recognition_copy(rendered: str, language_code: str) -> bool:
    marker_groups = VEHICLE_RECOGNITION_MARKERS.get(language_code, VEHICLE_RECOGNITION_MARKERS["en"])
    normalized = rendered.casefold()
    return all(any(marker in normalized for marker in group) for group in marker_groups)


def render_official_pickup_copy(stop_name: str, language: str, pickup_time: str, cruise_time: time | None = None) -> str | None:
    language_code = (language or "en").lower()
    templates = OFFICIAL_PICKUP_COPY.get(language_code) or OFFICIAL_PICKUP_COPY["en"]
    template = templates.get(stop_name)
    template_language = language_code
    if not template:
        template = OFFICIAL_PICKUP_COPY["en"].get(stop_name)
        template_language = "en"
    if not template:
        return None
    cruise_time_text = _format_time(cruise_time, pickup_time)
    arrival_time_text = _arrival_time_for_cruise(cruise_time, pickup_time)
    rendered = template.format(
        pickup_time=pickup_time,
        cruise_time=cruise_time_text,
        arrival_time=arrival_time_text,
    )
    if stop_name in NO_VEHICLE_PICKUP_POINTS:
        return rendered
    if _has_vehicle_recognition_copy(rendered, template_language):
        return rendered
    vehicle_sentence = VEHICLE_MARKING_SENTENCE.get(language_code, VEHICLE_MARKING_SENTENCE["en"])
    return f"{rendered} {vehicle_sentence}"
